version: '3'

services:
  localenv-example-php:
    container_name: localenv-example-php
    build: .
    command: ["php", "-S", "0.0.0.0:8081", "-t", "public"]
    ports:
      - "8081:8081"
    volumes:
      - ${PWD}:/var/www:delegated
      - ~/.composer/auth.json:/root/.composer/auth.json:ro
    networks:
      - localenv_network
    environment:
      APP_REDIS_HOST: global-redis
      APP_REDIS_PORT: 6379
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"

networks:
  localenv_network:
    external: true
