services:
  localenv-example-php:
    container_name: localenv-example-php
    build: .
    command: ["php", "-S", "0.0.0.0:8081", "-t", "public"]
    ports:
      - "8081:8081"
    volumes:
      - ${PWD}:/var/www:delegated
      - ~/.composer/auth.json:/root/.composer/auth.json:ro
    networks:
      - localenv_network
    environment:
      APP_MYSQL_HOST: global-mysql
      APP_MYSQL_PORT: 3306
      APP_MYSQL_USER: mysql
      APP_MYSQL_PASSWORD: superdupersecret
      APP_MYSQL_DATABASE: localenv

      APP_POSTGRES_HOST: global-postgres
      APP_POSTGRES_PORT: 5432
      APP_POSTGRES_USER: postgres
      APP_POSTGRES_PASSWORD: P@ssw0rd
      APP_POSTGRES_DATABASE: localenv

      APP_REDIS_HOST: global-redis
      APP_REDIS_PORT: 6379
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"

networks:
  localenv_network:
    external: true
